//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing FFMPEG.
        /// </summary>
        internal static string Form1_Form1_Missing_FFMPEG {
            get {
                return ResourceManager.GetString("Form1_Form1_Missing_FFMPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application uses FFMPEG for it&apos;s conversion. Please select where ffmpeg.exe can be found.
        /// </summary>
        internal static string Form1_Form1_This_application_uses_FFMPEG_for_it_s_conversion__Please_select_where_ffmpeg_exe_can_be_found {
            get {
                return ResourceManager.GetString("Form1_Form1_This_application_uses_FFMPEG_for_it_s_conversion__Please_select_where" +
                        "_ffmpeg_exe_can_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input file.
        /// </summary>
        internal static string Form1_onStartConversion_Invalid_input_file {
            get {
                return ResourceManager.GetString("Form1_onStartConversion_Invalid_input_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid output file.
        /// </summary>
        internal static string Form1_onStartConversion_Invalid_output_file {
            get {
                return ResourceManager.GetString("Form1_onStartConversion_Invalid_output_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input file selected.
        /// </summary>
        internal static string Form1_onStartConversion_No_input_file_selected {
            get {
                return ResourceManager.GetString("Form1_onStartConversion_No_input_file_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No output file selected.
        /// </summary>
        internal static string Form1_onStartConversion_No_output_file_selected {
            get {
                return ResourceManager.GetString("Form1_onStartConversion_No_output_file_selected", resourceCulture);
            }
        }
    }
}
